shift:
  start: 0 # 0x0000 First position of Basic Multilingual Plane (BMP)
  end: 65535 # 0xFFFF Last position of Basic Multilingual Plane (BMP)
#  start: 65 # First position as A in Unicode
#  end: 88 # Last position as Z in Unicode
